// Principales régions viticoles françaises : départements couverts (pour la carte),
// cépages majeurs, terroir et appellations phares.
// `aliases` sert à retrouver les bouteilles de la cave dont le champ « Région » correspond.

export const REGIONS_VITICOLES = [
  {
    id: "champagne",
    name: "Champagne",
    color: "#d8b45a",
    depts: ["51", "10", "02"],
    aliases: ["champagne"],
    rouges: ["Pinot noir", "Meunier"],
    blancs: ["Chardonnay"],
    terroir: "Sous-sol de craie qui régule l'humidité, climat frais à double influence océanique et continentale : idéal pour des raisins vifs, base des vins effervescents.",
    appellations: ["Champagne", "Coteaux champenois", "Rosé des Riceys"],
    styles: "Effervescents (blanc de blancs, blanc de noirs, rosés), quelques vins tranquilles.",
  },
  {
    id: "alsace",
    name: "Alsace",
    color: "#9db35a",
    depts: ["67", "68"],
    aliases: ["alsace"],
    rouges: ["Pinot noir"],
    blancs: ["Riesling", "Gewurztraminer", "Pinot gris", "Muscat", "Sylvaner", "Pinot blanc"],
    terroir: "Mosaïque de sols (granite, grès, schiste, calcaire, marnes) au pied des Vosges, qui abritent le vignoble des pluies : l'un des climats les plus secs de France.",
    appellations: ["Alsace", "Alsace Grand Cru", "Crémant d'Alsace"],
    styles: "Blancs secs aromatiques, vendanges tardives et sélections de grains nobles.",
  },
  {
    id: "bourgogne",
    name: "Bourgogne",
    color: "#8e1b2f",
    depts: ["21", "71", "89"],
    aliases: ["bourgogne", "chablis", "burgundy"],
    rouges: ["Pinot noir", "Gamay"],
    blancs: ["Chardonnay", "Aligoté", "Sauvignon (Saint-Bris)"],
    terroir: "Calcaires et marnes du Jurassique, découpés en « climats » (parcelles) classés au patrimoine mondial ; climat semi-continental.",
    appellations: ["Chablis", "Gevrey-Chambertin", "Vosne-Romanée", "Pommard", "Meursault", "Puligny-Montrachet", "Mercurey", "Pouilly-Fuissé"],
    styles: "Rouges fins et élégants, grands blancs de garde, Crémant de Bourgogne.",
  },
  {
    id: "beaujolais",
    name: "Beaujolais",
    color: "#b0476a",
    depts: ["69"],
    aliases: ["beaujolais"],
    rouges: ["Gamay"],
    blancs: ["Chardonnay"],
    terroir: "Granites et schistes au nord (les dix crus), argilo-calcaires « pierres dorées » au sud.",
    appellations: ["Morgon", "Moulin-à-Vent", "Fleurie", "Brouilly", "Juliénas", "Saint-Amour", "Beaujolais-Villages"],
    styles: "Rouges fruités et gouleyants, crus plus structurés capables de vieillir.",
  },
  {
    id: "jura",
    name: "Jura",
    color: "#c9a227",
    depts: ["39"],
    aliases: ["jura"],
    rouges: ["Poulsard", "Trousseau", "Pinot noir"],
    blancs: ["Savagnin", "Chardonnay"],
    terroir: "Marnes grises et bleues et calcaires sur les coteaux du Revermont ; climat continental aux hivers rudes.",
    appellations: ["Arbois", "Château-Chalon", "L'Étoile", "Côtes du Jura", "Crémant du Jura"],
    styles: "Vin jaune (élevage sous voile), vin de paille, Macvin, blancs oxydatifs ou ouillés.",
  },
  {
    id: "savoie",
    name: "Savoie & Bugey",
    color: "#5b8db8",
    depts: ["73", "74", "01"],
    aliases: ["savoie", "bugey"],
    rouges: ["Mondeuse", "Gamay", "Pinot noir"],
    blancs: ["Jacquère", "Altesse (Roussette)", "Bergeron (Roussanne)", "Chasselas"],
    terroir: "Éboulis calcaires et moraines glaciaires sur des pentes alpines ; climat montagnard tempéré par les lacs.",
    appellations: ["Vin de Savoie (Apremont, Chignin-Bergeron, Arbin)", "Roussette de Savoie", "Bugey", "Bugey-Cerdon"],
    styles: "Blancs vifs et légers, rouges poivrés de Mondeuse, effervescents.",
  },
  {
    id: "rhone",
    name: "Vallée du Rhône",
    color: "#a0402a",
    depts: ["07", "26", "84", "30"],
    aliases: ["rhône", "rhone", "côtes du rhône", "cotes du rhone"],
    rouges: ["Syrah", "Grenache", "Mourvèdre", "Cinsault", "Carignan"],
    blancs: ["Viognier", "Marsanne", "Roussanne", "Grenache blanc", "Clairette"],
    terroir: "Au nord, coteaux de granite très pentus (Syrah) ; au sud, galets roulés, sables et argiles sous un climat méditerranéen balayé par le mistral.",
    appellations: ["Côte-Rôtie", "Condrieu", "Hermitage", "Cornas", "Saint-Joseph", "Châteauneuf-du-Pape", "Gigondas", "Vacqueyras", "Tavel"],
    styles: "Rouges épicés et puissants, blancs amples et floraux, rosés de Tavel.",
  },
  {
    id: "provence",
    name: "Provence",
    color: "#f19bb0",
    depts: ["83", "13", "04", "06"],
    aliases: ["provence", "bandol"],
    rouges: ["Grenache", "Cinsault", "Syrah", "Mourvèdre", "Tibouren"],
    blancs: ["Rolle (Vermentino)", "Clairette", "Ugni blanc", "Sémillon"],
    terroir: "Calcaires à l'ouest, schistes et roches cristallines des Maures à l'est ; soleil intense et mistral.",
    appellations: ["Côtes de Provence", "Bandol", "Cassis", "Palette", "Coteaux d'Aix-en-Provence", "Bellet"],
    styles: "Rosés pâles et frais (près de 90 % de la production), rouges de garde de Bandol.",
  },
  {
    id: "corse",
    name: "Corse",
    color: "#7a4a8f",
    depts: ["2A", "2B"],
    aliases: ["corse"],
    rouges: ["Nielluccio", "Sciaccarellu", "Grenache"],
    blancs: ["Vermentinu"],
    terroir: "Granites au sud et à l'ouest, schistes du Cap Corse, îlot calcaire de Patrimonio ; climat méditerranéen tempéré par la mer et le relief.",
    appellations: ["Patrimonio", "Ajaccio", "Vin de Corse", "Muscat du Cap Corse"],
    styles: "Rouges et rosés aromatiques (maquis), blancs salins, muscats doux.",
  },
  {
    id: "languedoc",
    name: "Languedoc",
    color: "#c0573a",
    depts: ["34", "11"],
    aliases: ["languedoc", "corbières", "corbieres", "minervois"],
    rouges: ["Grenache", "Syrah", "Mourvèdre", "Carignan", "Cinsault"],
    blancs: ["Grenache blanc", "Picpoul", "Bourboulenc", "Roussanne", "Chardonnay (Limoux)", "Mauzac (Limoux)"],
    terroir: "Schistes (Faugères, Saint-Chinian), calcaires et galets entre garrigue et mer ; climat méditerranéen chaud et sec.",
    appellations: ["Languedoc", "Pic Saint-Loup", "Faugères", "Saint-Chinian", "Corbières", "Minervois", "Picpoul de Pinet", "Blanquette de Limoux"],
    styles: "Rouges généreux et épicés, blancs méridionaux, effervescents de Limoux.",
  },
  {
    id: "roussillon",
    name: "Roussillon",
    color: "#e07b39",
    depts: ["66"],
    aliases: ["roussillon", "banyuls", "maury", "collioure"],
    rouges: ["Grenache", "Carignan", "Syrah", "Mourvèdre"],
    blancs: ["Grenache blanc & gris", "Macabeu", "Muscat"],
    terroir: "Schistes noirs, granites et arènes au pied des Pyrénées ; le plus chaud et sec de France, balayé par la tramontane.",
    appellations: ["Banyuls", "Maury", "Rivesaltes", "Collioure", "Côtes du Roussillon Villages"],
    styles: "Vins doux naturels (Banyuls, Maury, Muscat de Rivesaltes) et rouges secs puissants.",
  },
  {
    id: "sud-ouest",
    name: "Sud-Ouest",
    color: "#6b2d5c",
    depts: ["24", "47", "46", "82", "31", "81", "12", "32", "40", "64", "65"],
    aliases: ["sud-ouest", "sud ouest", "cahors", "madiran", "gaillac", "bergerac", "jurançon", "jurancon", "gascogne", "armagnac"],
    rouges: ["Malbec (Côt)", "Tannat", "Négrette", "Fer servadou", "Merlot", "Cabernet franc"],
    blancs: ["Petit & Gros Manseng", "Mauzac", "Colombard", "Sémillon", "Sauvignon", "Muscadelle"],
    terroir: "Terrasses du Lot (Cahors), argilo-calcaires et galets, coteaux pyrénéens ; influences atlantique et montagnarde.",
    appellations: ["Cahors", "Madiran", "Jurançon", "Gaillac", "Bergerac", "Monbazillac", "Fronton", "Irouléguy", "Côtes de Gascogne"],
    styles: "Rouges tanniques de garde, blancs secs ou moelleux (Jurançon, Monbazillac), Armagnac.",
  },
  {
    id: "bordeaux",
    name: "Bordeaux",
    color: "#63001f",
    depts: ["33"],
    aliases: ["bordeaux", "médoc", "medoc", "saint-émilion", "saint-emilion", "pomerol", "graves", "sauternes"],
    rouges: ["Merlot", "Cabernet sauvignon", "Cabernet franc", "Petit verdot", "Malbec"],
    blancs: ["Sémillon", "Sauvignon blanc", "Muscadelle"],
    terroir: "Graves (galets et graviers) sur la rive gauche, argilo-calcaires et argiles sur la rive droite ; climat océanique adouci par la Gironde.",
    appellations: ["Margaux", "Pauillac", "Saint-Julien", "Saint-Estèphe", "Pessac-Léognan", "Saint-Émilion", "Pomerol", "Sauternes", "Entre-Deux-Mers"],
    styles: "Rouges d'assemblage de garde, blancs secs, liquoreux de Sauternes et Barsac.",
  },
  {
    id: "loire",
    name: "Val de Loire",
    color: "#3f8f7f",
    depts: ["44", "49", "37", "41", "18", "58", "45", "85", "36", "03", "63", "42"],
    aliases: ["loire", "sancerre", "muscadet", "anjou", "saumur", "touraine", "vouvray", "chinon"],
    rouges: ["Cabernet franc", "Gamay", "Pinot noir", "Grolleau", "Côt"],
    blancs: ["Chenin", "Sauvignon blanc", "Melon de Bourgogne", "Chardonnay"],
    terroir: "Gneiss et schistes du Pays nantais, schistes de l'Anjou noir, tuffeau de Saumur et Touraine, silex et calcaires kimméridgiens de Sancerre ; climat océanique devenant continental vers l'est.",
    appellations: ["Muscadet", "Savennières", "Saumur-Champigny", "Chinon", "Bourgueil", "Vouvray", "Sancerre", "Pouilly-Fumé", "Coteaux du Layon"],
    styles: "Blancs secs vifs à liquoreux, rouges frais de Cabernet franc, Crémant de Loire.",
  },
  {
    id: "charentes",
    name: "Charentes (Cognac)",
    color: "#b0702a",
    depts: ["16", "17"],
    aliases: ["cognac", "charente", "charentes"],
    rouges: ["Merlot", "Cabernet (Pineau rouge)"],
    blancs: ["Ugni blanc", "Colombard", "Folle blanche"],
    terroir: "Craies de la Grande et Petite Champagne, groies et sables vers l'océan ; climat océanique doux.",
    appellations: ["Cognac", "Pineau des Charentes", "Vin de pays Charentais"],
    styles: "Eaux-de-vie de Cognac, Pineau (mistelle), vins blancs légers.",
  },
];

export const deptToRegion = new Map(REGIONS_VITICOLES.flatMap((r) => r.depts.map((d) => [d, r])));
